name: docker-build

on:
  workflow_dispatch:
    branches:
      - 'main'

jobs:
  docker:
    runs-on: ubuntu-latest
    permissions:
        contents: read
        packages: write
    env:
      IMAGE_NAME: my_nginx
    steps:
      - 
        name: set lower case owner name
        run: echo "OWNER_LC=${OWNER,,}" >>${GITHUB_ENV}
        env:
          OWNER: '${{ github.repository_owner }}'
      # -
      #   name: Checkout
      #   uses: actions/checkout@v3
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: "${{ github.server_url }}/${{ github.repository }}.git#${{ github.ref }}:${{ env.IMAGE_NAME }}"
          push: true
          tags: ghcr.io/${{ env.OWNER_LC }}/${{ env.IMAGE_NAME }}:latest
      # -
      #   name: デバッグ中
      #   run: docker image ls

      # -
      #   name: Save image
      #   run: docker save tobotobo/${{ env.IMAGE_NAME }}:latest ${{ env.IMAGE_NAME }}.tar
      # - 
      #   uses: actions/upload-artifact@v3
      #   with:
      #     name: ${{ env.IMAGE_NAME }}
      #     path: ./${{ env.IMAGE_NAME }}.tar